In [54]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder
import joblib

In [55]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/insurance.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [56]:
df.shape

(1338, 7)

In [57]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [58]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [59]:
df.duplicated().sum()
df.drop_duplicates(inplace = True)
df.duplicated().sum()

np.int64(0)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1337 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1337 non-null   int64
 1   sex       1337 non-null   object
 2   bmi       1337 non-null   float64
 3   children  1337 non-null   int64
 4   smoker    1337 non-null   object
 5   region    1337 non-null   object
 6   charges   1337 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 83.6+ KB

In [61]:
df.describe()

               age          bmi     children       charges
count  1337.000000  1337.000000  1337.000000   1337.000000
mean     39.222139    30.663452     1.095737  13279.121487
std      14.044333     6.100468     1.205571  12110.359656
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.290000     0.000000   4746.344000
50%      39.000000    30.400000     1.000000   9386.161300
75%      51.000000    34.700000     2.000000  16657.717450
max      64.000000    53.130000     5.000000  63770.428010

In [62]:
encoder = LabelEncoder()
df['sex'] = encoder.fit_transform(df['sex'])
df['smoker'] = encoder.fit_transform(df['smoker'])
df['region'] = encoder.fit_transform(df['region'])
df

      age  sex     bmi  children  smoker  region      charges
0      19    0  27.900         0       1       3  16884.92400
1      18    1  33.770         1       0       2   1725.55230
2      28    1  33.000         3       0       2   4449.46200
3      33    1  22.705         0       0       1  21984.47061
4      32    1  28.880         0       0       1   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    1  30.970         3       0       1  10600.54830
1334   18    0  31.920         0       0       0   2205.98080
1335   18    0  36.850         0       0       2   1629.83350
1336   21    0  25.800         0       0       3   2007.94500
1337   61    0  29.070         0       1       1  29141.36030

[1337 rows x 7 columns]

In [63]:
x = df[['age', 'sex', 'bmi', 'children', 'smoker', 'region']]
y = df['charges']

In [64]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [65]:
model = DecisionTreeRegressor(max_depth=4, random_state=42)
model.fit(x_train, y_train)

DecisionTreeRegressor(max_depth=4, random_state=42)

In [66]:
y_pred = model.predict(x_test)
df_comparison = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred}).reset_index(drop = True)
df_comparison

          Actual     Predicted
0     8688.85885  11016.035202
1     5708.86700   5685.043924
2    11436.73815  11016.035202
3    38746.35510  40778.860983
4     4463.20510   5685.043924
..           ...           ...
263  13831.11520  15296.948835
264  13887.20400  15296.948835
265   3925.75820   7543.387800
266  47403.88000  47542.034247
267   8534.67180  11016.035202

[268 rows x 2 columns]

#Notes
I first trained a Decision Tree Regressor using the default parameters. Then I tuned the max_depth hyperparameter by testing multiple values (2, 4, 6, 8, 10). The model with max_depth=4 achieved the highest R² score (0.8981) and the lowest MAE and MSE. I also experimented with min_samples_split, but it did not outperform the model using max_depth=4. Therefore, I selected the max_depth=4 model as the final model.

In [67]:
MAE = mean_absolute_error(y_test, y_pred)
print('Mean Absolute Error:', MAE)
MSE = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', MSE)
R2 = r2_score(y_test, y_pred)
print('R2 SCORE:', R2)

Mean Absolute Error: 2591.668249425639
Mean Squared Error: 18722739.93515944
R2 SCORE: 0.8981109002695451

In [68]:
joblib.dump(model, "insurance_model.pkl")

['insurance_model.pkl']